<?php $tables['forms'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'optin-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'name' => (strstr($_GET['page'], 'categories') ? __('Parent category ID', 'optin-manager') : __('Category ID', 'optin-manager')), 'width' => 12),
'name' => array('type' => 'text', 'name' => __('Name', 'optin-manager'), 'width' => 18, 'searchby' => __('the name', 'optin-manager')),
'description' => array('type' => 'text', 'name' => __('Description', 'optin-manager'), 'width' => 18, 'searchby' => __('the description', 'optin-manager')),
'keywords' => array('type' => 'text', 'name' => __('Keywords', 'optin-manager'), 'width' => 18, 'searchby' => __('the keywords', 'optin-manager')),
'gift_download_url' => array('type' => 'text', 'name' => __('Gift download URL', 'optin-manager'), 'width' => 18, 'searchby' => __('the gift download URL', 'optin-manager')),
'instructions' => array('type' => 'text', 'name' => __('Instructions to the prospect', 'optin-manager'), 'width' => 18, 'searchby' => __('the instructions to the prospect', 'optin-manager')),
'date' => array('type' => 'datetime', 'name' => __('Creation date', 'optin-manager'), 'width' => 18, 'searchby' => __('the creation date', 'optin-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Creation date (UTC)', 'optin-manager'), 'width' => 18, 'searchby' => __('the creation date (UTC)', 'optin-manager')),
'autoresponder' => array('type' => 'text', 'name' => __('Autoresponder', 'optin-manager'), 'width' => 12, 'searchby' => __('the autoresponder', 'optin-manager')),
'autoresponder_list' => array('type' => 'text', 'name' => __('Autoresponder list', 'optin-manager'), 'width' => 15, 'searchby' => __('the autoresponder list', 'optin-manager')),
'code' => array('type' => 'text', 'name' => __('Code', 'optin-manager'), 'width' => 18, 'searchby' => __('the code', 'optin-manager')),
'unfilled_field_message' => array('type' => 'text', 'name' => __('Unfilled field\'s message', 'optin-manager'), 'width' => 18, 'searchby' => __('the unfilled field\'s message', 'optin-manager')),
'invalid_email_address_message' => array('type' => 'text', 'name' => __('Invalid email address message', 'optin-manager'), 'width' => 18, 'searchby' => __('the invalid email address message', 'optin-manager')),
'registration_confirmation_url' => array('type' => 'text', 'name' => __('Registration confirmation URL', 'optin-manager'), 'width' => 18, 'searchby' => __('the registration confirmation URL', 'optin-manager')),
'prospects_initial_status' => array('type' => 'text', 'name' => __('Prospects initial status', 'optin-manager'), 'width' => 15),
'registration_confirmation_email_sent' => array('type' => 'text', 'name' => __('Registration confirmation email sent', 'optin-manager'), 'width' => 15),
'registration_confirmation_email_sender' => array('type' => 'text', 'name' => __('Sender of the registration confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the sender of the registration confirmation email', 'optin-manager')),
'registration_confirmation_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the registration confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the receiver of the registration confirmation email', 'optin-manager')),
'registration_confirmation_email_subject' => array('type' => 'text', 'name' => __('Subject of the registration confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the subject of the registration confirmation email', 'optin-manager')),
'registration_confirmation_email_body' => array('type' => 'text', 'name' => __('Body of the registration confirmation email', 'optin-manager'), 'width' => 18, 'searchby' => __('the body of the registration confirmation email', 'optin-manager')),
'registration_notification_email_sent' => array('type' => 'text', 'name' => __('Registration notification email sent', 'optin-manager'), 'width' => 15),
'registration_notification_email_sender' => array('type' => 'text', 'name' => __('Sender of the registration notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the sender of the registration notification email', 'optin-manager')),
'registration_notification_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the registration notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the receiver of the registration notification email', 'optin-manager')),
'registration_notification_email_subject' => array('type' => 'text', 'name' => __('Subject of the registration notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the subject of the registration notification email', 'optin-manager')),
'registration_notification_email_body' => array('type' => 'text', 'name' => __('Body of the registration notification email', 'optin-manager'), 'width' => 18, 'searchby' => __('the body of the registration notification email', 'optin-manager')),
'prospect_subscribed_to_members_areas' => array('type' => 'text', 'name' => __('Prospects subscribed to a member area', 'optin-manager'), 'width' => 18),
'prospect_members_areas' => array('type' => 'text', 'name' => __('Prospects members areas', 'optin-manager'), 'width' => 12, 'searchby' => __('the prospects members areas', 'optin-manager')),
'registration_custom_instructions_executed' => array('type' => 'text', 'name' => __('Custom instructions executed', 'optin-manager'), 'width' => 15),
'registration_custom_instructions' => array('type' => 'text', 'name' => __('PHP code of the custom instructions', 'optin-manager'), 'width' => 18, 'searchby' => __('the PHP code of the custom instructions', 'optin-manager')),
'activation_confirmation_email_sent' => array('type' => 'text', 'name' => __('Activation confirmation email sent', 'optin-manager'), 'width' => 15),
'activation_confirmation_email_sender' => array('type' => 'text', 'name' => __('Sender of the activation confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the sender of the activation confirmation email', 'optin-manager')),
'activation_confirmation_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the activation confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the receiver of the activation confirmation email', 'optin-manager')),
'activation_confirmation_email_subject' => array('type' => 'text', 'name' => __('Subject of the activation confirmation email', 'optin-manager'), 'width' => 15, 'searchby' => __('the subject of the activation confirmation email', 'optin-manager')),
'activation_confirmation_email_body' => array('type' => 'text', 'name' => __('Body of the activation confirmation email', 'optin-manager'), 'width' => 18, 'searchby' => __('the body of the activation confirmation email', 'optin-manager')),
'activation_notification_email_sent' => array('type' => 'text', 'name' => __('Activation notification email sent', 'optin-manager'), 'width' => 15),
'activation_notification_email_sender' => array('type' => 'text', 'name' => __('Sender of the activation notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the sender of the activation notification email', 'optin-manager')),
'activation_notification_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the activation notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the receiver of the activation notification email', 'optin-manager')),
'activation_notification_email_subject' => array('type' => 'text', 'name' => __('Subject of the activation notification email', 'optin-manager'), 'width' => 15, 'searchby' => __('the subject of the activation notification email', 'optin-manager')),
'activation_notification_email_body' => array('type' => 'text', 'name' => __('Body of the activation notification email', 'optin-manager'), 'width' => 18, 'searchby' => __('the body of the activation notification email', 'optin-manager')),
'affiliation_enabled' => array('type' => 'text', 'name' => __('Affiliation enabled', 'optin-manager'), 'width' => 12),
'commission_amount' => array('type' => 'text', 'name' => __('Commission amount', 'optin-manager'), 'width' => 12, 'searchby' => __('the commission amount', 'optin-manager')),
'commission2_enabled' => array('type' => 'text', 'name' => __('Commission enabled', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 12),
'commission2_amount' => array('type' => 'text', 'name' => __('Commission amount', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 15, 'searchby' => __('the commission amount', 'optin-manager').' '.__('(level 2)', 'optin-manager')));

$tables['forms_categories'] = $tables['forms'];

$tables['prospects'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'optin-manager'), 'width' => 5),
'first_name' => array('type' => 'text', 'name' => __('First name', 'optin-manager'), 'width' => 12, 'searchby' => __('the first name', 'optin-manager')),
'last_name' => array('type' => 'text', 'name' => __('Last name', 'optin-manager'), 'width' => 12, 'searchby' => __('the last name', 'optin-manager')),
'email_address' => array('type' => 'text', 'name' => __('Email address', 'optin-manager'), 'width' => 15, 'searchby' => __('the email address', 'optin-manager')),
'website_name' => array('type' => 'text', 'name' => __('Website', 'optin-manager'), 'width' => 15, 'searchby' => __('the website name', 'optin-manager')),
'website_url' => array('type' => 'text', 'name' => __('Website URL', 'optin-manager'), 'width' => 18, 'searchby' => __('the website URL', 'optin-manager')),
'address' => array('type' => 'text', 'name' => __('Address', 'optin-manager'), 'width' => 15, 'searchby' => __('the address', 'optin-manager')),
'postcode' => array('type' => 'text', 'name' => __('Postcode', 'optin-manager'), 'width' => 9, 'searchby' => __('the postcode', 'optin-manager')),
'town' => array('type' => 'text', 'name' => __('Town', 'optin-manager'), 'width' => 12, 'searchby' => __('the town', 'optin-manager')),
'country' => array('type' => 'text', 'name' => __('Country', 'optin-manager'), 'width' => 12, 'searchby' => __('the country', 'optin-manager')),
'phone_number' => array('type' => 'text', 'name' => __('Phone number', 'optin-manager'), 'width' => 12, 'searchby' => __('the phone number', 'optin-manager')),
'ip_address' => array('type' => 'text', 'name' => __('IP address', 'optin-manager'), 'width' => 12, 'searchby' => __('the IP address', 'optin-manager')),
'user_agent' => array('type' => 'text', 'name' => __('User agent', 'optin-manager'), 'width' => 24, 'searchby' => __('the user agent', 'optin-manager')),
'referring_url' => array('type' => 'text', 'name' => __('Referring URL', 'optin-manager'), 'width' => 18, 'searchby' => __('the referring URL', 'optin-manager')),
'status' => array('type' => 'text', 'default' => 'active', 'name' => __('Status', 'optin-manager'), 'width' => 12),
'form_id' => array('type' => 'int', 'name' => __('Form ID', 'optin-manager'), 'width' => 9),
'date' => array('type' => 'datetime', 'name' => __('Registration date', 'optin-manager'), 'width' => 18, 'searchby' => __('the registration date', 'optin-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Registration date (UTC)', 'optin-manager'), 'width' => 18, 'searchby' => __('the registration date (UTC)', 'optin-manager')),
'autoresponder' => array('type' => 'text', 'name' => __('Autoresponder', 'optin-manager'), 'width' => 12, 'searchby' => __('the autoresponder', 'optin-manager')),
'autoresponder_list' => array('type' => 'text', 'name' => __('Autoresponder list', 'optin-manager'), 'width' => 12, 'searchby' => __('the autoresponder list', 'optin-manager')),
'referrer' => array('type' => 'text', 'name' => __('Referrer', 'optin-manager'), 'width' => 12, 'searchby' => __('the referrer', 'optin-manager')),
'commission_amount' => array('type' => 'dec(12,2)', 'name' => __('Commission amount', 'optin-manager'), 'width' => 12, 'searchby' => __('the commission amount', 'optin-manager')),
'commission_status' => array('type' => 'text', 'name' => __('Commission status', 'optin-manager'), 'width' => 12),
'commission_payment_date' => array('type' => 'datetime', 'name' => __('Commission\'s payment date', 'optin-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date', 'optin-manager')),
'commission_payment_date_utc' => array('type' => 'datetime', 'name' => __('Commission\'s payment date (UTC)', 'optin-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date (UTC)', 'optin-manager')),
'referrer2' => array('type' => 'text', 'name' => __('Referrer', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 15, 'searchby' => __('the referrer', 'optin-manager').' '.__('(level 2)', 'optin-manager')),
'commission2_amount' => array('type' => 'dec(12,2)', 'name' => __('Commission amount', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 15, 'searchby' => __('the commission amount', 'optin-manager').' '.__('(level 2)', 'optin-manager')),
'commission2_status' => array('type' => 'text', 'name' => __('Commission status', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 15),
'commission2_payment_date' => array('type' => 'datetime', 'name' => __('Commission\'s payment date', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date', 'optin-manager').' '.__('(level 2)', 'optin-manager')),
'commission2_payment_date_utc' => array('type' => 'datetime', 'name' => __('Commission\'s payment date (UTC)', 'optin-manager').' '.__('(level 2)', 'optin-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date (UTC)', 'optin-manager').' '.__('(level 2)', 'optin-manager')));