<?php $tables['orders'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'commerce-manager'), 'width' => 5),
'product_id' => array('type' => 'int', 'name' => __('Product ID', 'commerce-manager'), 'width' => 9, 'searchby' => __('the product ID', 'commerce-manager')),
'quantity' => array('type' => 'int', 'name' => __('Quantity', 'commerce-manager'), 'width' => 9, 'searchby' => __('the quantity', 'commerce-manager')),
'price' => array('type' => 'dec(12,2)', 'name' => __('Global price', 'commerce-manager'), 'width' => 9, 'searchby' => __('the global price', 'commerce-manager')),
'tax' => array('type' => 'dec(12,2)', 'name' => __('Tax', 'commerce-manager'), 'width' => 9, 'searchby' => __('the tax', 'commerce-manager')),
'tax_included_in_price' => array('type' => 'text', 'name' => __('Tax included in price', 'commerce-manager'), 'width' => 12),
'shipping_cost' => array('type' => 'dec(12,2)', 'name' => __('Shipping cost', 'commerce-manager'), 'width' => 9, 'searchby' => __('the shipping cost', 'commerce-manager')),
'amount' => array('type' => 'dec(12,2)', 'name' => __('Amount', 'commerce-manager'), 'width' => 12, 'searchby' => __('the amount', 'commerce-manager')),
'payment_mode' => array('type' => 'text', 'name' => __('Payment mode', 'commerce-manager'), 'width' => 12, 'searchby' => __('the payment mode', 'commerce-manager')),
'transaction_number' => array('type' => 'text', 'name' => __('Transaction number', 'commerce-manager'), 'width' => 15, 'searchby' => __('the transaction number', 'commerce-manager')),
'transaction_cost' => array('type' => 'dec(12,2)', 'name' => __('Transaction cost', 'commerce-manager'), 'width' => 9, 'searchby' => __('the transaction cost', 'commerce-manager')),
'instructions' => array('type' => 'text', 'name' => __('Instructions to the seller', 'commerce-manager'), 'width' => 18, 'searchby' => __('the instructions to the seller', 'commerce-manager')),
'shipping_address' => array('type' => 'text', 'name' => __('Shipping address', 'commerce-manager'), 'width' => 18, 'searchby' => __('the shipping address', 'commerce-manager')),
'date' => array('type' => 'datetime', 'name' => __('Date', 'commerce-manager'), 'width' => 18, 'searchby' => __('the date', 'commerce-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Date (UTC)', 'commerce-manager'), 'width' => 18, 'searchby' => __('the date (UTC)', 'commerce-manager')),
'status' => array('type' => 'text', 'name' => __('Status', 'commerce-manager'), 'width' => 12),
'refund_date' => array('type' => 'datetime', 'name' => __('Refund date', 'commerce-manager'), 'width' => 18, 'searchby' => __('the refund date', 'commerce-manager')),
'refund_date_utc' => array('type' => 'datetime', 'name' => __('Refund date (UTC)', 'commerce-manager'), 'width' => 18, 'searchby' => __('the refund date (UTC)', 'commerce-manager')),
'first_name' => array('type' => 'text', 'name' => __('First name', 'commerce-manager'), 'width' => 12, 'searchby' => __('the first name', 'commerce-manager')),
'last_name' => array('type' => 'text', 'name' => __('Last name', 'commerce-manager'), 'width' => 12, 'searchby' => __('the last name', 'commerce-manager')),
'email_address' => array('type' => 'text', 'name' => __('Email address', 'commerce-manager'), 'width' => 15, 'searchby' => __('the email address', 'commerce-manager')),
'website_name' => array('type' => 'text', 'name' => __('Website', 'commerce-manager'), 'width' => 15, 'searchby' => __('the website name', 'commerce-manager')),
'website_url' => array('type' => 'text', 'name' => __('Website URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the website URL', 'commerce-manager')),
'address' => array('type' => 'text', 'name' => __('Address', 'commerce-manager'), 'width' => 15, 'searchby' => __('the address', 'commerce-manager')),
'postcode' => array('type' => 'text', 'name' => __('Postcode', 'commerce-manager'), 'width' => 9, 'searchby' => __('the postcode', 'commerce-manager')),
'town' => array('type' => 'text', 'name' => __('Town', 'commerce-manager'), 'width' => 12, 'searchby' => __('the town', 'commerce-manager')),
'country' => array('type' => 'text', 'name' => __('Country', 'commerce-manager'), 'width' => 12, 'searchby' => __('the country', 'commerce-manager')),
'phone_number' => array('type' => 'text', 'name' => __('Phone number', 'commerce-manager'), 'width' => 12, 'searchby' => __('the phone number', 'commerce-manager')),
'ip_address' => array('type' => 'text', 'name' => __('IP address', 'commerce-manager'), 'width' => 12, 'searchby' => __('the IP address', 'commerce-manager')),
'user_agent' => array('type' => 'text', 'name' => __('User agent', 'commerce-manager'), 'width' => 24, 'searchby' => __('the user agent', 'commerce-manager')),
'referring_url' => array('type' => 'text', 'name' => __('Referring URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the referring URL', 'commerce-manager')),
'referrer' => array('type' => 'text', 'name' => __('Referrer', 'commerce-manager'), 'width' => 12, 'searchby' => __('the referrer', 'commerce-manager')),
'commission_amount' => array('type' => 'dec(12,2)', 'name' => __('Commission amount', 'commerce-manager'), 'width' => 12, 'searchby' => __('the commission amount', 'commerce-manager')),
'commission_payment' => array('type' => 'text', 'name' => __('Commission payment', 'commerce-manager'), 'width' => 12),
'commission_status' => array('type' => 'text', 'name' => __('Commission status', 'commerce-manager'), 'width' => 12),
'commission_payment_date' => array('type' => 'datetime', 'name' => __('Commission\'s payment date', 'commerce-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date', 'commerce-manager')),
'commission_payment_date_utc' => array('type' => 'datetime', 'name' => __('Commission\'s payment date (UTC)', 'commerce-manager'), 'width' => 18, 'searchby' => __('the commission\'s payment date (UTC)', 'commerce-manager')));

$tables['products'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'commerce-manager'), 'width' => 5),
'name' => array('type' => 'text', 'name' => __('Name', 'commerce-manager'), 'width' => 18, 'searchby' => __('the name', 'commerce-manager')),
'price' => array('type' => 'text', 'name' => __('Price', 'commerce-manager'), 'width' => 9, 'searchby' => __('the price', 'commerce-manager')),
'reference' => array('type' => 'text', 'name' => __('Reference', 'commerce-manager'), 'width' => 12, 'searchby' => __('the reference', 'commerce-manager')),
'description' => array('type' => 'text', 'name' => __('Description', 'commerce-manager'), 'width' => 18, 'searchby' => __('the description', 'commerce-manager')),
'url' => array('type' => 'text', 'name' => __('URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the URL', 'commerce-manager')),
'thumbnail_url' => array('type' => 'text', 'name' => __('Thumbnail URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the thumbnail URL', 'commerce-manager')),
'downloadable' => array('type' => 'text', 'name' => __('Downloadable', 'commerce-manager'), 'width' => 9),
'download_url' => array('type' => 'text', 'name' => __('Download URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the download URL', 'commerce-manager')),
'instructions' => array('type' => 'text', 'name' => __('Instructions to the customer', 'commerce-manager'), 'width' => 18, 'searchby' => __('the instructions to the customer', 'commerce-manager')),
'date' => array('type' => 'datetime', 'name' => __('Launch date', 'commerce-manager'), 'width' => 18, 'searchby' => __('the launch date', 'commerce-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Launch date (UTC)', 'commerce-manager'), 'width' => 18, 'searchby' => __('the launch date (UTC)', 'commerce-manager')),
'available_quantity' => array('type' => 'text', 'name' => __('Available quantity', 'commerce-manager'), 'width' => 12, 'searchby' => __('the available quantity', 'commerce-manager')),
'sales_count' => array('type' => 'int', 'name' => __('Sales count', 'commerce-manager'), 'width' => 12, 'searchby' => __('the sales count', 'commerce-manager')),
'refunds_count' => array('type' => 'int', 'name' => __('Refunds count', 'commerce-manager'), 'width' => 12, 'searchby' => __('the refunds count', 'commerce-manager')),
'purchase_button_url' => array('type' => 'text', 'name' => __('Purchase button URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the purchase button URL', 'commerce-manager')),
'purchase_button_text' => array('type' => 'text', 'name' => __('Purchase button text', 'commerce-manager'), 'width' => 18, 'searchby' => __('the purchase button text', 'commerce-manager')),
'order_confirmation_url' => array('type' => 'text', 'name' => __('Order confirmation URL', 'commerce-manager'), 'width' => 18, 'searchby' => __('the order confirmation URL', 'commerce-manager')),
'orders_initial_status' => array('type' => 'text', 'name' => __('Orders initial status', 'commerce-manager'), 'width' => 15),
'tax_applied' => array('type' => 'text', 'name' => __('Tax applied', 'commerce-manager'), 'width' => 9),
'tax_included_in_price' => array('type' => 'text', 'name' => __('Tax included in price', 'commerce-manager'), 'width' => 12),
'tax_percentage' => array('type' => 'text', 'name' => __('Tax percentage', 'commerce-manager'), 'width' => 12, 'searchby' => __('the tax percentage', 'commerce-manager')),
'shipping_address_required' => array('type' => 'text', 'name' => __('Shipping address required', 'commerce-manager'), 'width' => 12),
'shipping_cost' => array('type' => 'text', 'name' => __('Shipping cost', 'commerce-manager'), 'width' => 12, 'searchby' => __('the shipping cost', 'commerce-manager')),
'sandbox_enabled' => array('type' => 'text', 'name' => __('Sandbox mode enabled', 'commerce-manager'), 'width' => 12),
'paypal_email_address' => array('type' => 'text', 'name' => __('PayPal email address', 'commerce-manager'), 'width' => 15, 'searchby' => __('the PayPal email address', 'commerce-manager')),
'order_confirmation_email_sent' => array('type' => 'text', 'name' => __('Order confirmation email sent', 'commerce-manager'), 'width' => 15),
'order_confirmation_email_sender' => array('type' => 'text', 'name' => __('Sender of the order confirmation email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the sender of the order confirmation email', 'commerce-manager')),
'order_confirmation_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the order confirmation email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the receiver of the order confirmation email', 'commerce-manager')),
'order_confirmation_email_subject' => array('type' => 'text', 'name' => __('Subject of the order confirmation email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the subject of the order confirmation email', 'commerce-manager')),
'order_confirmation_email_body' => array('type' => 'text', 'name' => __('Body of the order confirmation email', 'commerce-manager'), 'width' => 18, 'searchby' => __('the body of the order confirmation email', 'commerce-manager')),
'order_notification_email_sent' => array('type' => 'text', 'name' => __('Order notification email sent', 'commerce-manager'), 'width' => 15),
'order_notification_email_sender' => array('type' => 'text', 'name' => __('Sender of the order notification email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the sender of the order notification email', 'commerce-manager')),
'order_notification_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the order notification email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the receiver of the order notification email', 'commerce-manager')),
'order_notification_email_subject' => array('type' => 'text', 'name' => __('Subject of the order notification email', 'commerce-manager'), 'width' => 15, 'searchby' => __('the subject of the order notification email', 'commerce-manager')),
'order_notification_email_body' => array('type' => 'text', 'name' => __('Body of the order notification email', 'commerce-manager'), 'width' => 18, 'searchby' => __('the body of the order notification email', 'commerce-manager')),
'customer_subscribed_to_autoresponder' => array('type' => 'text', 'name' => __('Customers subscribed to an autoresponder list', 'commerce-manager'), 'width' => 18),
'customer_autoresponder' => array('type' => 'text', 'name' => __('Customers autoresponder', 'commerce-manager'), 'width' => 12, 'searchby' => __('the customers autoresponder', 'commerce-manager')),
'customer_autoresponder_list' => array('type' => 'text', 'name' => __('Customers autoresponder list', 'commerce-manager'), 'width' => 15, 'searchby' => __('the customers autoresponder list', 'commerce-manager')),
'affiliation_enabled' => array('type' => 'text', 'name' => __('Affiliation enabled', 'commerce-manager'), 'width' => 12),
'commission_type' => array('type' => 'text', 'name' => __('Commission type', 'commerce-manager'), 'width' => 12),
'commission_amount' => array('type' => 'text', 'name' => __('Commission amount', 'commerce-manager'), 'width' => 12, 'searchby' => __('the commission amount', 'commerce-manager')),
'commission_percentage' => array('type' => 'text', 'name' => __('Commission percentage', 'commerce-manager'), 'width' => 12, 'searchby' => __('the commission percentage', 'commerce-manager')),
'commission_payment' => array('type' => 'text', 'name' => __('Commission payment', 'commerce-manager'), 'width' => 12),
'first_sale_winner' => array('type' => 'text', 'name' => __('First sale winner', 'commerce-manager'), 'width' => 12),
'registration_required' => array('type' => 'text', 'name' => __('Registration required', 'commerce-manager'), 'width' => 12));