<?php $tables['members'] = array(
'id' => array('type' => 'int', 'modules' => array('personal-informations'), 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'modules' => array('personal-informations'), 'name' => __('Category ID', 'membership-manager'), 'width' => 12),
'login' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Login name', 'membership-manager'), 'width' => 12, 'searchby' => __('the login name', 'membership-manager')),
'password' => array('type' => 'text', 'modules' => array('personal-informations')),
'first_name' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('First name', 'membership-manager'), 'width' => 12, 'searchby' => __('the first name', 'membership-manager')),
'last_name' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Last name', 'membership-manager'), 'width' => 12, 'searchby' => __('the last name', 'membership-manager')),
'email_address' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Email address', 'membership-manager'), 'width' => 15, 'searchby' => __('the email address', 'membership-manager')),
'website_name' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Website', 'membership-manager'), 'width' => 15, 'searchby' => __('the website name', 'membership-manager')),
'website_url' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Website URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the website URL', 'membership-manager')),
'address' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Address', 'membership-manager'), 'width' => 15, 'searchby' => __('the address', 'membership-manager')),
'postcode' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Postcode', 'membership-manager'), 'width' => 9, 'searchby' => __('the postcode', 'membership-manager')),
'town' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Town', 'membership-manager'), 'width' => 12, 'searchby' => __('the town', 'membership-manager')),
'country' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Country', 'membership-manager'), 'width' => 12, 'searchby' => __('the country', 'membership-manager')),
'phone_number' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Phone number', 'membership-manager'), 'width' => 12, 'searchby' => __('the phone number', 'membership-manager')),
'ip_address' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('IP address', 'membership-manager'), 'width' => 12, 'searchby' => __('the IP address', 'membership-manager')),
'user_agent' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('User agent', 'membership-manager'), 'width' => 24, 'searchby' => __('the user agent', 'membership-manager')),
'referring_url' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Referring URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the referring URL', 'membership-manager')),
'status' => array('type' => 'text', 'default' => 'active', 'modules' => array('personal-informations'), 'name' => __('Status', 'membership-manager'), 'width' => 12),
'members_areas' => array('type' => 'text', 'modules' => array('personal-informations'), 'name' => __('Members areas', 'membership-manager'), 'width' => 12),
'date' => array('type' => 'datetime', 'modules' => array('personal-informations'), 'name' => __('Registration date', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'modules' => array('personal-informations'), 'name' => __('Registration date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration date (UTC)', 'membership-manager')));

$tables['members_areas'] = array(
'id' => array('type' => 'int', 'modules' => array('general-informations'), 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'modules' => array('general-informations'), 'name' => (strstr($_GET['page'], 'categories') ? __('Parent category ID', 'membership-manager') : __('Category ID', 'membership-manager')), 'width' => 12),
'name' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Name', 'membership-manager'), 'width' => 18, 'searchby' => __('the name', 'membership-manager')),
'description' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Description', 'membership-manager'), 'width' => 18, 'searchby' => __('the description', 'membership-manager')),
'keywords' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Keywords', 'membership-manager'), 'width' => 18, 'searchby' => __('the keywords', 'membership-manager')),
'url' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the URL', 'membership-manager')),
'instructions' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Instructions to the member', 'membership-manager'), 'width' => 18, 'searchby' => __('the instructions to the member', 'membership-manager')),
'members_areas' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Included members areas', 'membership-manager'), 'width' => 18),
'date' => array('type' => 'datetime', 'modules' => array('general-informations'), 'name' => __('Creation date', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'modules' => array('general-informations'), 'name' => __('Creation date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date (UTC)', 'membership-manager')),
'registration_confirmation_url' => array('type' => 'text', 'modules' => array('registration'), 'name' => __('Registration confirmation URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration confirmation URL', 'membership-manager')),
'members_initial_category_id' => array('type' => 'text', 'modules' => array('registration'), 'name' => __('Members initial category ID', 'membership-manager'), 'width' => 15),
'members_initial_status' => array('type' => 'text', 'modules' => array('registration'), 'name' => __('Members initial status', 'membership-manager'), 'width' => 15),
'activation_confirmation_url' => array('type' => 'text', 'modules' => array('registration'), 'name' => __('Activation confirmation URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the activation confirmation URL', 'membership-manager')),
'registration_confirmation_email_sent' => array('type' => 'text', 'modules' => array('registration-confirmation-email'), 'name' => __('Registration confirmation email sent', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_sender' => array('type' => 'text', 'modules' => array('registration-confirmation-email'), 'name' => __('Sender of the registration confirmation email', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_receiver' => array('type' => 'text', 'modules' => array('registration-confirmation-email'), 'name' => __('Receiver of the registration confirmation email', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_subject' => array('type' => 'text', 'modules' => array('registration-confirmation-email'), 'name' => __('Subject of the registration confirmation email', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_body' => array('type' => 'text', 'modules' => array('registration-confirmation-email'), 'name' => __('Body of the registration confirmation email', 'membership-manager'), 'width' => 18),
'registration_notification_email_sent' => array('type' => 'text', 'modules' => array('registration-notification-email'), 'name' => __('Registration notification email sent', 'membership-manager'), 'width' => 15),
'registration_notification_email_sender' => array('type' => 'text', 'modules' => array('registration-notification-email'), 'name' => __('Sender of the registration notification email', 'membership-manager'), 'width' => 15),
'registration_notification_email_receiver' => array('type' => 'text', 'modules' => array('registration-notification-email'), 'name' => __('Receiver of the registration notification email', 'membership-manager'), 'width' => 15),
'registration_notification_email_subject' => array('type' => 'text', 'modules' => array('registration-notification-email'), 'name' => __('Subject of the registration notification email', 'membership-manager'), 'width' => 15),
'registration_notification_email_body' => array('type' => 'text', 'modules' => array('registration-notification-email'), 'name' => __('Body of the registration notification email', 'membership-manager'), 'width' => 18),
'member_subscribed_to_autoresponder' => array('type' => 'text', 'modules' => array('autoresponders'), 'name' => __('Members subscribed to an autoresponder list', 'membership-manager'), 'width' => 18),
'member_autoresponder' => array('type' => 'text', 'modules' => array('autoresponders'), 'name' => __('Members autoresponder', 'membership-manager'), 'width' => 12, 'searchby' => __('the members autoresponder', 'membership-manager')),
'member_autoresponder_list' => array('type' => 'text', 'modules' => array('autoresponders'), 'name' => __('Members autoresponder list', 'membership-manager'), 'width' => 15, 'searchby' => __('the members autoresponder list', 'membership-manager')),
'member_subscribed_as_a_client' => array('type' => 'text', 'modules' => array('registration-as-a-client'), 'name' => __('Members subscribed as clients', 'membership-manager'), 'width' => 18),
'member_client_category_id' => array('type' => 'text', 'modules' => array('registration-as-a-client'), 'name' => __('Members client category ID', 'membership-manager'), 'width' => 15),
'member_client_status' => array('type' => 'text', 'modules' => array('registration-as-a-client'), 'name' => __('Members client status', 'membership-manager'), 'width' => 15),
'commerce_registration_confirmation_email_sent' => array('type' => 'text', 'modules' => array('registration-as-a-client'), 'name' => __('Registration confirmation email sent', 'membership-manager').' '.__('(Commerce)', 'membership-manager'), 'width' => 15),
'commerce_registration_notification_email_sent' => array('type' => 'text', 'modules' => array('registration-as-a-client'), 'name' => __('Registration notification email sent', 'membership-manager').' '.__('(Commerce)', 'membership-manager'), 'width' => 15),
'member_subscribed_to_affiliate_program' => array('type' => 'text', 'modules' => array('registration-to-affiliate-program'), 'name' => __('Members subscribed to affiliate program', 'membership-manager'), 'width' => 18),
'member_affiliate_category_id' => array('type' => 'text', 'modules' => array('registration-to-affiliate-program'), 'name' => __('Members affiliate category ID', 'membership-manager'), 'width' => 15),
'member_affiliate_status' => array('type' => 'text', 'modules' => array('registration-to-affiliate-program'), 'name' => __('Members affiliate status', 'membership-manager'), 'width' => 15),
'affiliation_registration_confirmation_email_sent' => array('type' => 'text', 'modules' => array('registration-to-affiliate-program'), 'name' => __('Registration confirmation email sent', 'membership-manager').' '.__('(Affiliation)', 'membership-manager'), 'width' => 15),
'affiliation_registration_notification_email_sent' => array('type' => 'text', 'modules' => array('registration-to-affiliate-program'), 'name' => __('Registration notification email sent', 'membership-manager').' '.__('(Affiliation)', 'membership-manager'), 'width' => 15),
'member_subscribed_as_a_user' => array('type' => 'text', 'modules' => array('wordpress'), 'name' => __('Members subscribed as users', 'membership-manager'), 'width' => 18),
'member_user_role' => array('type' => 'text', 'modules' => array('wordpress'), 'name' => __('Members user role', 'membership-manager'), 'width' => 15),
'registration_custom_instructions_executed' => array('type' => 'text', 'modules' => array('custom-instructions'), 'name' => __('Custom instructions executed', 'membership-manager'), 'width' => 15),
'registration_custom_instructions' => array('type' => 'text', 'modules' => array('custom-instructions'), 'name' => __('PHP code of the custom instructions', 'membership-manager'), 'width' => 18),
'activation_confirmation_email_sent' => array('type' => 'text', 'modules' => array('activation-confirmation-email'), 'name' => __('Activation confirmation email sent', 'membership-manager'), 'width' => 15),
'activation_confirmation_email_sender' => array('type' => 'text', 'modules' => array('activation-confirmation-email'), 'name' => __('Sender of the activation confirmation email', 'membership-manager'), 'width' => 15),
'activation_confirmation_email_receiver' => array('type' => 'text', 'modules' => array('activation-confirmation-email'), 'name' => __('Receiver of the activation confirmation email', 'membership-manager'), 'width' => 15),
'activation_confirmation_email_subject' => array('type' => 'text', 'modules' => array('activation-confirmation-email'), 'name' => __('Subject of the activation confirmation email', 'membership-manager'), 'width' => 15),
'activation_confirmation_email_body' => array('type' => 'text', 'modules' => array('activation-confirmation-email'), 'name' => __('Body of the activation confirmation email', 'membership-manager'), 'width' => 18));

$tables['members_areas_categories'] = $tables['members_areas'];

$tables['members_categories'] = array(
'id' => array('type' => 'int', 'modules' => array('general-informations'), 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'modules' => array('general-informations'), 'name' => __('Parent category ID', 'membership-manager'), 'width' => 12),
'name' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Name', 'membership-manager'), 'width' => 18, 'searchby' => __('the name', 'membership-manager')),
'description' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Description', 'membership-manager'), 'width' => 18, 'searchby' => __('the description', 'membership-manager')),
'keywords' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Keywords', 'membership-manager'), 'width' => 18, 'searchby' => __('the keywords', 'membership-manager')),
'members_areas' => array('type' => 'text', 'modules' => array('general-informations'), 'name' => __('Members areas', 'membership-manager'), 'width' => 12),
'date' => array('type' => 'datetime', 'modules' => array('general-informations'), 'name' => __('Creation date', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'modules' => array('general-informations'), 'name' => __('Creation date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date (UTC)', 'membership-manager')));