<?php global $wpdb;
$option_name = 'affiliation_manager_affiliates';
$table_name = $wpdb->prefix.'affiliation_manager_affiliates';
$no_items = __('No affiliates', 'affiliation-manager');
$_GET['singular'] = __('affiliate', 'affiliation-manager');
$_GET['plural'] = __('affiliates', 'affiliation-manager');

$_GET['columns_names'] = array(
'id' => __('ID', 'affiliation-manager'),
'login' => __('Login name', 'affiliation-manager'),
'first_name' => __('First name', 'affiliation-manager'),
'last_name' => __('Last name', 'affiliation-manager'),
'email_address' => __('Email address', 'affiliation-manager'),
'paypal_email_address' => __('PayPal email address', 'affiliation-manager'),
'website_name' => __('Website', 'affiliation-manager'),
'website_url' => __('Website URL', 'affiliation-manager'),
'address' => __('Address', 'affiliation-manager'),
'postcode' => __('Postcode', 'affiliation-manager'),
'town' => __('Town', 'affiliation-manager'),
'country' => __('Country', 'affiliation-manager'),
'phone_number' => __('Phone number', 'affiliation-manager'),
'commission_percentage' => __('Commission percentage', 'affiliation-manager'),
'commission_amount' => __('Commission amount', 'affiliation-manager'),
'date' => __('Registration date', 'affiliation-manager'),
'date_utc' => __('Registration date (UTC)', 'affiliation-manager'),
'user_agent' => __('User agent', 'affiliation-manager'),
'ip_address' => __('IP address', 'affiliation-manager'),
'referring_url' => __('Referring URL', 'affiliation-manager'),
'referrer' => __('Referrer', 'affiliation-manager'));

$_GET['columns_widths'] = array(
'id' => 5,
'login' => 12,
'first_name' => 12,
'last_name' => 12,
'email_address' => 15,
'paypal_email_address' => 15,
'website_name' => 15,
'website_url' => 18,
'address' => 15,
'postcode' => 9,
'town' => 12,
'country' => 12,
'phone_number' => 12,
'commission_percentage' => 12,
'commission_amount' => 12,
'date' => 18,
'date_utc' => 18,
'user_agent' => 24,
'ip_address' => 12,
'referring_url' => 18,
'referrer' => 12);